# This file was generated by GoReleaser. DO NOT EDIT.
class Filewatcher < Formula
  desc "a filewatcher"
  homepage "https://github.com/filewatcher"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/broothie/filewatcher/releases/download/v0.0.1/filewatcher_0.0.1_darwin_amd64.tar.gz"
    sha256 "8b572e929a7789e96a3d0dbe789092fcd90cf2544eec3d19fd0fa69d51cbd44b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/broothie/filewatcher/releases/download/v0.0.1/filewatcher_0.0.1_linux_amd64.tar.gz"
      sha256 "dfd7b3db887e46da359b491f610826aa895bcdace0e942972aca8fe08f29aa49"
    end
  end

  def install
    bin.install "filewatcher"
  end
end
